plugins {
    id 'com.android.application'
}

android {
    compileSdk = 37

    defaultConfig {
        applicationId = 'com.andy.simplecidgetter'
        minSdk = 23
        targetSdk = 37
        versionCode = 37
        versionName = "1.11"

        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            shrinkResources = true
            optimization {
                enable = true // Enables code and resource optimizations.
            }
        }
    }

    buildFeatures {
        viewBinding = true
    }
    namespace = 'com.andy.simplecidgetter'
    buildToolsVersion '37.0.0'
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
}

allprojects {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.deprecation = true
        }
    }
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}